### ISSUE TITLE
Add Vapor to DevIcon

### ISSUE THREAD

**Issue by haIIux** [vapor/website#100]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to help promote Vapor and the Vapor brand in numerous spots using the [DevIcon library](https://devicon.dev).

**Describe the solution you'd like**
Create a issue on the [DevIcon Repo](https://github.com/devicons/devicon) to request the Vapor branding be added.

**Comment by 0xTim** [comment]
https://github.com/devicons/devicon/issues/2238
