### ISSUE TITLE
Routing issue: vapor docs url without trailing '/' times out.

### ISSUE THREAD

**Issue by marc-medley** [vapor/website#17]
The vapor doc URLs `https://docs.vapor.codes/2.0/` and `https://docs.vapor.codes/3.0/` responds OK.

However, [`https://docs.vapor.codes/2.0`](https://docs.vapor.codes/2.0) and [`https://docs.vapor.codes/3.0`](https://docs.vapor.codes/3.0) timeout.

After the connections times out, then the URLs that timed out show as `https://docs.vapor.codes:8080/2.0/` and `https://docs.vapor.codes:8080/3.0/` in the browser navigaton bar.

So, my exiting vapor doc bookmarks (that used to work) needed to be updated with the appended `/`.

**Comment by tanner0101** [comment]
That issue should be created here: https://github.com/vapor/documentation. This repo is for http://vapor.codes. Not sure if there's anything we can do about that, but we can take a look once the issue is properly placed 👍

**Comment by marc-medley** [comment]
relocated to [https://github.com/vapor/documentation/issues/319](https://github.com/vapor/documentation/issues/319)
