### ISSUE TITLE
Reference to potential redesign of vapor.codes

### ISSUE THREAD

**Issue by vegetablestabber** [vapor/website#22]
Look no further! Here's the inspiration you need for the website's betterment: [Figma file](https://www.figma.com/file/HdDdBPnQ1O0GurX75LFgbwvb/Vapor) (still working on it; feel free to comment in Figma or over here extensively)

**Comment by ava-gunn** [comment]
I would be willing to work on this. I have experience in Vue, but am a beginner in Swift.
