### ISSUE TITLE
Get Started button on vapor.codes goes to v3 documentation

### ISSUE THREAD

**Issue by mattt** [vapor/website#64]
If you visit https://vapor.codes, you see a "Get Started" call-to-action button at the top.

<img width="960" alt="Screen Shot 2020-05-19 at 11 28 16" src="https://user-images.githubusercontent.com/7659/82364292-f1a4c000-99c3-11ea-82f8-1b21c394e197.png">

Clicking that button takes you to https://docs.vapor.codes/3.0/install/macos/, which is a page in the documentation for version 3.

Now that version 4 is available, this link should take you here instead: https://docs.vapor.codes/4.0/install/macos/

**Comment by mattt** [comment]
Also, clicking the "Docs" link in the header navigates to https://docs.vapor.codes/, which then redirects to https://docs.vapor.codes/3.0 instead of https://docs.vapor.codes/4.0

See: https://github.com/vapor/docs/issues/489

**Comment by 0xTim** [comment]
@tanner0101 I'm assuming we're waiting for Fluent and Toolbox to be tagged before defaulting to 4.0?

**Comment by tanner0101** [comment]
Yeah we're gonna be in kind of an awkward phase for a bit. The question is how long. The two extremes are:

### Update the website, toolbox, and docs to point to Vapor 4 by default _now_

Pros: 
- People will start using Vapor 4 by default
- It's not confusing that Vapor 4 has been released but the site still points to 3

Cons:
- Most people will probably be using other packages like Fluent, JWT, Queues, APNS, etc. 
- These packages are not officially released yet, people may not want to be forced into using release candidates
- Unreleased packages are not yet documented and may have known bugs that aren't fixed yet

### Wait until all packages are documented and released first

Pros:
- People can opt into using Vapor 4 at their own discretion
- This means opting into using pre-release packages that can lack documentation and be more buggy

Cons:
- The state of the site, docs, toolbox, and vapor version will be confusing during this time
- More people starting on Vapor 3 who will need to migrate to 4

--- 

I think swapping the site, docs, and toolbox over somewhere in between these two extremes would be best. Given that Fluent is the most highly used package, waiting until that is released could be a good compromise. The safest option would be to wait until everything is released though. 

The other thing to consider is that updating the website will take a non trivial amount of time (there's a new version already in the works). Putting that in the middle of the release process means delaying the release.

**Comment by 0xTim** [comment]
My vote would be to migrate the toolbox and docs site as soon as Fluent is released, since those are those most popular packages and the toolbox integrates with Fluent directly. Things like Leaf can be marked as "RC - coming soon, please ask in Discord" in the docs to avoid confusion.

For the website, would it be possible to just update the button and wait until the release is finished to do the full overhaul?

**Comment by tanner0101** [comment]
> My vote would be to migrate the toolbox and docs site as soon as Fluent is released

+1

> For the website, would it be possible to just update the button and wait until the release is finished to do the full overhaul?

Yeah that's a reasonable compromise. At least the code snippet that references Vapor 3 code should be changed, but that is easy enough.

**Comment by mattt** [comment]
Thanks for thinking through mitigation strategies. Even if things are a bit awkward right now, I think it's important to set clear expectations up front.

Curious to know, what was the motivation behind releasing Vapor 4.0 ahead of the corresponding versions of Leaf and Fluent?

**Comment by tanner0101** [comment]
@mattt I don't want to hold up releases that are ready for the sake of other packages that are not. Not everyone uses Leaf and Fluent and if we were still waiting on those nothing would be released yet. In an ideal world everything would go out at the same time, maybe some day! That's a good goal to work toward.

**Comment by oliverwebr** [comment]
I just got confused by this. The **nav link** points to https://docs.vapor.codes which redirects to **v4.0**
https://github.com/vapor/website/blob/edd9f47b5a66a6872ba952dba47b787698932343/src/vapor/nav.vue#L87

But the **getting started button** still points to **v3.0**
https://github.com/vapor/website/blob/edd9f47b5a66a6872ba952dba47b787698932343/src/vapor/common/callToAction.vue#L44

**Comment by tanner0101** [comment]
The site has been updated now 👍
