### ISSUE TITLE
http://vapor.codes has incorrect link to Redis repository

### ISSUE THREAD

**Issue by sotrosh** [vapor/website#67]
Hi,

Not sure if I should post bug here but found out that vapor.codes website has incorrect url when I click on Redis button. It should navigate to this repository instead of APNS. 
<img width="1443" alt="Screen Shot 2020-06-23 at 11 40 09 AM" src="https://user-images.githubusercontent.com/1019784/85418741-88c2e180-b547-11ea-9bce-811d28f980f9.png">

**Comment by grundoon** [comment]
(moved issue to https://github.com/vapor/website)

**Comment by grundoon** [comment]
Thanks @sotrosh! – fixed in https://github.com/vapor/website/pull/68

**Comment by sotrosh** [comment]
It still navigates to https://github.com/vapor/apns when I click on Redis button. Not sure if it already in production. Thanks anyway.
